import streamlit as st
st.title("Recipe Generator App")
st.text("Text Technology Project, Class of 21-22")
st.text("Submitted to: Kristen Jung")
st.text("Submitted by: Silvia Cunico, Akshat Gupta")

st.sidebar.write("What Recipe Generator does? [link](https://share.streamlit.io/mesmith027/streamlit_webapps/main/MC_pi/streamlit_app.py)")
st.sidebar.write("About Dataset")
st.sidebar.write("XML Version of Data")
st.sidebar.write("DTD Version of Data")
st.sidebar.write("XSLT Version of Data")
st.sidebar.write("EDA on Data")
st.sidebar.write("About Machine Learning Model")
st.sidebar.write("Use of Databases")
st.sidebar.write("Documentation")
st.sidebar.write("Slides")
st.text_input("Enter Ingredients")
st.button("Generate")